spring:
  h2.console:
    enabled: true
    path: /console
    settings.web-allow-others: true
  datasource.url: jdbc:h2:file:/C:/Workspace/dbs/2do/testdb
  
management:
  endpoints:
    web:
      exposure:
        include: '*'