spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "secret"

logging:
  level:
    root: INFO
  file.name: C:/Workspace/logs/2do/logs.log
  pattern.file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 9000