spring:
  h2.console:
    enabled: true
    path: /console
    settings.web-allow-others: true
  datasource.url: jdbc:h2:mem:dev
  
management:
  endpoints:
    web:
      exposure:
        include: '*'